export const Questions = [
  {
    prompt: "React Js is a free and Open- source front-end.....",
    optionA: "JavaScript library",
    optionB: "Bootstrap library",
    optionC: "CSS library",
    optionD: " None of the Above",
    answer: "A",
  },
  {
    prompt: "React Js had written in ....",
    optionA: "JavaScript",
    optionB: "python",
    optionC: "java",
    optionD: "php",
    answer: "A",
  },
  {
    prompt: ".... is used in React Js to increase performance",
    optionA: "Virtual DOM",
    optionB: "Original DOM",
    optionC: "Both",
    optionD: "None",
    answer: "A",
  },
  {
    prompt: "What is Babel?",
    optionA: "JavaScript interperter",
    optionB: "JavaScript transpiler",
    optionC: "JavaScript Compiler",
    optionD: "None",
    answer: "C",
  },
  {
    prompt: " React is used mainly for building....",
    optionA: "Database",
    optionB: "User interface",
    optionC: "Connectivity",
    optionD: "Design platform",
    answer: "B",
  },
  {
    prompt: "What is the smallest building block of React Js",
    optionA: "Props",
    optionB: "Elements",
    optionC: "Component",
    optionD: "None",
    answer: "C",
  },
];
